#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCSharp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_gestion_franca")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_gf_elemento(tbl_gf_elemento instance);
    partial void Updatetbl_gf_elemento(tbl_gf_elemento instance);
    partial void Deletetbl_gf_elemento(tbl_gf_elemento instance);
    partial void Inserttbl_gf_tecnico(tbl_gf_tecnico instance);
    partial void Updatetbl_gf_tecnico(tbl_gf_tecnico instance);
    partial void Deletetbl_gf_tecnico(tbl_gf_tecnico instance);
    partial void Inserttbl_gf_elementos_tecnico(tbl_gf_elementos_tecnico instance);
    partial void Updatetbl_gf_elementos_tecnico(tbl_gf_elementos_tecnico instance);
    partial void Deletetbl_gf_elementos_tecnico(tbl_gf_elementos_tecnico instance);
    partial void Inserttbl_gf_sucursale(tbl_gf_sucursale instance);
    partial void Updatetbl_gf_sucursale(tbl_gf_sucursale instance);
    partial void Deletetbl_gf_sucursale(tbl_gf_sucursale instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_gestion_francaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_gf_elemento> tbl_gf_elementos
		{
			get
			{
				return this.GetTable<tbl_gf_elemento>();
			}
		}
		
		public System.Data.Linq.Table<tbl_gf_tecnico> tbl_gf_tecnicos
		{
			get
			{
				return this.GetTable<tbl_gf_tecnico>();
			}
		}
		
		public System.Data.Linq.Table<tbl_gf_elementos_tecnico> tbl_gf_elementos_tecnicos
		{
			get
			{
				return this.GetTable<tbl_gf_elementos_tecnico>();
			}
		}
		
		public System.Data.Linq.Table<tbl_gf_sucursale> tbl_gf_sucursales
		{
			get
			{
				return this.GetTable<tbl_gf_sucursale>();
			}
		}
		
		public System.Data.Linq.Table<vw_gf_elementos_por_tecnico> vw_gf_elementos_por_tecnicos
		{
			get
			{
				return this.GetTable<vw_gf_elementos_por_tecnico>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_gf_listar_tecnicos")]
		public ISingleResult<sp_gf_listar_tecnicosResult> sp_gf_listar_tecnicos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_gf_listar_tecnicosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gf_elementos")]
	public partial class tbl_gf_elemento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<int> _cod_elemento;
		
		private string _nom_elemento;
		
		private EntitySet<tbl_gf_elementos_tecnico> _tbl_gf_elementos_tecnicos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Oncod_elementoChanging(System.Nullable<int> value);
    partial void Oncod_elementoChanged();
    partial void Onnom_elementoChanging(string value);
    partial void Onnom_elementoChanged();
    #endregion
		
		public tbl_gf_elemento()
		{
			this._tbl_gf_elementos_tecnicos = new EntitySet<tbl_gf_elementos_tecnico>(new Action<tbl_gf_elementos_tecnico>(this.attach_tbl_gf_elementos_tecnicos), new Action<tbl_gf_elementos_tecnico>(this.detach_tbl_gf_elementos_tecnicos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_elemento", DbType="Int")]
		public System.Nullable<int> cod_elemento
		{
			get
			{
				return this._cod_elemento;
			}
			set
			{
				if ((this._cod_elemento != value))
				{
					this.Oncod_elementoChanging(value);
					this.SendPropertyChanging();
					this._cod_elemento = value;
					this.SendPropertyChanged("cod_elemento");
					this.Oncod_elementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_elemento", DbType="VarChar(750)")]
		public string nom_elemento
		{
			get
			{
				return this._nom_elemento;
			}
			set
			{
				if ((this._nom_elemento != value))
				{
					this.Onnom_elementoChanging(value);
					this.SendPropertyChanging();
					this._nom_elemento = value;
					this.SendPropertyChanged("nom_elemento");
					this.Onnom_elementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_elemento_tbl_gf_elementos_tecnico", Storage="_tbl_gf_elementos_tecnicos", ThisKey="id", OtherKey="id_elemento")]
		public EntitySet<tbl_gf_elementos_tecnico> tbl_gf_elementos_tecnicos
		{
			get
			{
				return this._tbl_gf_elementos_tecnicos;
			}
			set
			{
				this._tbl_gf_elementos_tecnicos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_gf_elementos_tecnicos(tbl_gf_elementos_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_elemento = this;
		}
		
		private void detach_tbl_gf_elementos_tecnicos(tbl_gf_elementos_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_elemento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gf_tecnicos")]
	public partial class tbl_gf_tecnico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<int> _cod_tecnico;
		
		private string _nom_tecnico;
		
		private long _id_sucursal;
		
		private EntitySet<tbl_gf_elementos_tecnico> _tbl_gf_elementos_tecnicos;
		
		private EntityRef<tbl_gf_sucursale> _tbl_gf_sucursale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Oncod_tecnicoChanging(System.Nullable<int> value);
    partial void Oncod_tecnicoChanged();
    partial void Onnom_tecnicoChanging(string value);
    partial void Onnom_tecnicoChanged();
    partial void Onid_sucursalChanging(long value);
    partial void Onid_sucursalChanged();
    #endregion
		
		public tbl_gf_tecnico()
		{
			this._tbl_gf_elementos_tecnicos = new EntitySet<tbl_gf_elementos_tecnico>(new Action<tbl_gf_elementos_tecnico>(this.attach_tbl_gf_elementos_tecnicos), new Action<tbl_gf_elementos_tecnico>(this.detach_tbl_gf_elementos_tecnicos));
			this._tbl_gf_sucursale = default(EntityRef<tbl_gf_sucursale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_tecnico", DbType="Int")]
		public System.Nullable<int> cod_tecnico
		{
			get
			{
				return this._cod_tecnico;
			}
			set
			{
				if ((this._cod_tecnico != value))
				{
					this.Oncod_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._cod_tecnico = value;
					this.SendPropertyChanged("cod_tecnico");
					this.Oncod_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_tecnico", DbType="VarChar(750)")]
		public string nom_tecnico
		{
			get
			{
				return this._nom_tecnico;
			}
			set
			{
				if ((this._nom_tecnico != value))
				{
					this.Onnom_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._nom_tecnico = value;
					this.SendPropertyChanged("nom_tecnico");
					this.Onnom_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sucursal", DbType="BigInt NOT NULL")]
		public long id_sucursal
		{
			get
			{
				return this._id_sucursal;
			}
			set
			{
				if ((this._id_sucursal != value))
				{
					if (this._tbl_gf_sucursale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sucursalChanging(value);
					this.SendPropertyChanging();
					this._id_sucursal = value;
					this.SendPropertyChanged("id_sucursal");
					this.Onid_sucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_tecnico_tbl_gf_elementos_tecnico", Storage="_tbl_gf_elementos_tecnicos", ThisKey="id", OtherKey="id_tecnico")]
		public EntitySet<tbl_gf_elementos_tecnico> tbl_gf_elementos_tecnicos
		{
			get
			{
				return this._tbl_gf_elementos_tecnicos;
			}
			set
			{
				this._tbl_gf_elementos_tecnicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_sucursale_tbl_gf_tecnico", Storage="_tbl_gf_sucursale", ThisKey="id_sucursal", OtherKey="id", IsForeignKey=true)]
		public tbl_gf_sucursale tbl_gf_sucursale
		{
			get
			{
				return this._tbl_gf_sucursale.Entity;
			}
			set
			{
				tbl_gf_sucursale previousValue = this._tbl_gf_sucursale.Entity;
				if (((previousValue != value) 
							|| (this._tbl_gf_sucursale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_gf_sucursale.Entity = null;
						previousValue.tbl_gf_tecnicos.Remove(this);
					}
					this._tbl_gf_sucursale.Entity = value;
					if ((value != null))
					{
						value.tbl_gf_tecnicos.Add(this);
						this._id_sucursal = value.id;
					}
					else
					{
						this._id_sucursal = default(long);
					}
					this.SendPropertyChanged("tbl_gf_sucursale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_gf_elementos_tecnicos(tbl_gf_elementos_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_tecnico = this;
		}
		
		private void detach_tbl_gf_elementos_tecnicos(tbl_gf_elementos_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_tecnico = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gf_elementos_tecnico")]
	public partial class tbl_gf_elementos_tecnico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _id_tecnico;
		
		private long _id_elemento;
		
		private System.Nullable<int> _cantidad_elemento;
		
		private EntityRef<tbl_gf_elemento> _tbl_gf_elemento;
		
		private EntityRef<tbl_gf_tecnico> _tbl_gf_tecnico;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onid_tecnicoChanging(long value);
    partial void Onid_tecnicoChanged();
    partial void Onid_elementoChanging(long value);
    partial void Onid_elementoChanged();
    partial void Oncantidad_elementoChanging(System.Nullable<int> value);
    partial void Oncantidad_elementoChanged();
    #endregion
		
		public tbl_gf_elementos_tecnico()
		{
			this._tbl_gf_elemento = default(EntityRef<tbl_gf_elemento>);
			this._tbl_gf_tecnico = default(EntityRef<tbl_gf_tecnico>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tecnico", DbType="BigInt NOT NULL")]
		public long id_tecnico
		{
			get
			{
				return this._id_tecnico;
			}
			set
			{
				if ((this._id_tecnico != value))
				{
					if (this._tbl_gf_tecnico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._id_tecnico = value;
					this.SendPropertyChanged("id_tecnico");
					this.Onid_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_elemento", DbType="BigInt NOT NULL")]
		public long id_elemento
		{
			get
			{
				return this._id_elemento;
			}
			set
			{
				if ((this._id_elemento != value))
				{
					if (this._tbl_gf_elemento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_elementoChanging(value);
					this.SendPropertyChanging();
					this._id_elemento = value;
					this.SendPropertyChanged("id_elemento");
					this.Onid_elementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_elemento", DbType="Int")]
		public System.Nullable<int> cantidad_elemento
		{
			get
			{
				return this._cantidad_elemento;
			}
			set
			{
				if ((this._cantidad_elemento != value))
				{
					this.Oncantidad_elementoChanging(value);
					this.SendPropertyChanging();
					this._cantidad_elemento = value;
					this.SendPropertyChanged("cantidad_elemento");
					this.Oncantidad_elementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_elemento_tbl_gf_elementos_tecnico", Storage="_tbl_gf_elemento", ThisKey="id_elemento", OtherKey="id", IsForeignKey=true)]
		public tbl_gf_elemento tbl_gf_elemento
		{
			get
			{
				return this._tbl_gf_elemento.Entity;
			}
			set
			{
				tbl_gf_elemento previousValue = this._tbl_gf_elemento.Entity;
				if (((previousValue != value) 
							|| (this._tbl_gf_elemento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_gf_elemento.Entity = null;
						previousValue.tbl_gf_elementos_tecnicos.Remove(this);
					}
					this._tbl_gf_elemento.Entity = value;
					if ((value != null))
					{
						value.tbl_gf_elementos_tecnicos.Add(this);
						this._id_elemento = value.id;
					}
					else
					{
						this._id_elemento = default(long);
					}
					this.SendPropertyChanged("tbl_gf_elemento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_tecnico_tbl_gf_elementos_tecnico", Storage="_tbl_gf_tecnico", ThisKey="id_tecnico", OtherKey="id", IsForeignKey=true)]
		public tbl_gf_tecnico tbl_gf_tecnico
		{
			get
			{
				return this._tbl_gf_tecnico.Entity;
			}
			set
			{
				tbl_gf_tecnico previousValue = this._tbl_gf_tecnico.Entity;
				if (((previousValue != value) 
							|| (this._tbl_gf_tecnico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_gf_tecnico.Entity = null;
						previousValue.tbl_gf_elementos_tecnicos.Remove(this);
					}
					this._tbl_gf_tecnico.Entity = value;
					if ((value != null))
					{
						value.tbl_gf_elementos_tecnicos.Add(this);
						this._id_tecnico = value.id;
					}
					else
					{
						this._id_tecnico = default(long);
					}
					this.SendPropertyChanged("tbl_gf_tecnico");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gf_sucursales")]
	public partial class tbl_gf_sucursale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<int> _cod_sucursal;
		
		private string _nom_sucursal;
		
		private EntitySet<tbl_gf_tecnico> _tbl_gf_tecnicos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Oncod_sucursalChanging(System.Nullable<int> value);
    partial void Oncod_sucursalChanged();
    partial void Onnom_sucursalChanging(string value);
    partial void Onnom_sucursalChanged();
    #endregion
		
		public tbl_gf_sucursale()
		{
			this._tbl_gf_tecnicos = new EntitySet<tbl_gf_tecnico>(new Action<tbl_gf_tecnico>(this.attach_tbl_gf_tecnicos), new Action<tbl_gf_tecnico>(this.detach_tbl_gf_tecnicos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_sucursal", DbType="Int")]
		public System.Nullable<int> cod_sucursal
		{
			get
			{
				return this._cod_sucursal;
			}
			set
			{
				if ((this._cod_sucursal != value))
				{
					this.Oncod_sucursalChanging(value);
					this.SendPropertyChanging();
					this._cod_sucursal = value;
					this.SendPropertyChanged("cod_sucursal");
					this.Oncod_sucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_sucursal", DbType="VarChar(250)")]
		public string nom_sucursal
		{
			get
			{
				return this._nom_sucursal;
			}
			set
			{
				if ((this._nom_sucursal != value))
				{
					this.Onnom_sucursalChanging(value);
					this.SendPropertyChanging();
					this._nom_sucursal = value;
					this.SendPropertyChanged("nom_sucursal");
					this.Onnom_sucursalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_gf_sucursale_tbl_gf_tecnico", Storage="_tbl_gf_tecnicos", ThisKey="id", OtherKey="id_sucursal")]
		public EntitySet<tbl_gf_tecnico> tbl_gf_tecnicos
		{
			get
			{
				return this._tbl_gf_tecnicos;
			}
			set
			{
				this._tbl_gf_tecnicos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_gf_tecnicos(tbl_gf_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_sucursale = this;
		}
		
		private void detach_tbl_gf_tecnicos(tbl_gf_tecnico entity)
		{
			this.SendPropertyChanging();
			entity.tbl_gf_sucursale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_gf_elementos_por_tecnico")]
	public partial class vw_gf_elementos_por_tecnico
	{
		
		private System.Nullable<int> _total;
		
		private long _id_tecnico;
		
		public vw_gf_elementos_por_tecnico()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tecnico", DbType="BigInt NOT NULL")]
		public long id_tecnico
		{
			get
			{
				return this._id_tecnico;
			}
			set
			{
				if ((this._id_tecnico != value))
				{
					this._id_tecnico = value;
				}
			}
		}
	}
	
	public partial class sp_gf_listar_tecnicosResult
	{
		
		private long _identificacion;
		
		private System.Nullable<int> _codigo;
		
		private string _tecnico;
		
		private string _sucursal;
		
		private System.Nullable<int> _total;
		
		public sp_gf_listar_tecnicosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificacion", DbType="BigInt NOT NULL")]
		public long identificacion
		{
			get
			{
				return this._identificacion;
			}
			set
			{
				if ((this._identificacion != value))
				{
					this._identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int")]
		public System.Nullable<int> codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tecnico", DbType="VarChar(750)")]
		public string tecnico
		{
			get
			{
				return this._tecnico;
			}
			set
			{
				if ((this._tecnico != value))
				{
					this._tecnico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sucursal", DbType="VarChar(250)")]
		public string sucursal
		{
			get
			{
				return this._sucursal;
			}
			set
			{
				if ((this._sucursal != value))
				{
					this._sucursal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
